const ISO_CODES: Record<string, string> = {
  "Alemanha": "de",
  "Argentina": "ar",
  "Argélia": "dz",
  "Austrália": "au",
  "Arábia Saudita": "sa",
  "África do Sul": "za",
  "Áustria": "at",
  "Bélgica": "be",
  "Bolívia": "bo",
  "Bósnia-Herzegovina": "ba",
  "Brasil": "br",
  "Cabo Verde": "cv",
  "Camarões": "cm",
  "Canadá": "ca",
  "Chile": "cl",
  "Colômbia": "co",
  "Coreia do Sul": "kr",
  "Costa do Marfim": "ci",
  "Costa Rica": "cr",
  "Croácia": "hr",
  "Curaçao": "cw",
  "Dinamarca": "dk",
  "EUA": "us",
  "Egito": "eg",
  "Equador": "ec",
  "Escócia": "gb-sct",
  "Espanha": "es",
  "França": "fr",
  "Gana": "gh",
  "Haiti": "ht",
  "Holanda": "nl",
  "Honduras": "hn",
  "Inglaterra": "gb-eng",
  "Indonésia": "id",
  "Iraque": "iq",
  "Irã": "ir",
  "Israel": "il",
  "Itália": "it",
  "Jamaica": "jm",
  "Japão": "jp",
  "Jordânia": "jo",
  "Marrocos": "ma",
  "México": "mx",
  "Nicarágua": "ni",
  "Nigéria": "ng",
  "Noruega": "no",
  "Nova Zelândia": "nz",
  "Panamá": "pa",
  "Paraguai": "py",
  "Peru": "pe",
  "Polônia": "pl",
  "Portugal": "pt",
  "Qatar": "qa",
  "Rep. Dem. Congo": "cd",
  "República Tcheca": "cz",
  "Romênia": "ro",
  "Rússia": "ru",
  "Senegal": "sn",
  "Suécia": "se",
  "Suíça": "ch",
  "Sérvia": "rs",
  "Tunísia": "tn",
  "Turquia": "tr",
  "Ucrânia": "ua",
  "Uruguai": "uy",
  "Uzbequistão": "uz",
  "Venezuela": "ve",
};

export function getFlagUrl(teamName: string): string | null {
  const code = ISO_CODES[teamName];
  if (!code) return null;
  return `https://flagcdn.com/w40/${code}.png`;
}
